Icon list
WildCodeSchool/lille-0919-js-projet3-shinyHedgehog pull request #10
Opened 2019-12-06 08:32 UTC by alimalone

2019-12-06 10:21 UTC, laurentmahieu submitted a review, later dismissed
ok

2019-12-06 12:58 UTC, laurentmahieu submitted a review, later dismissed

2019-12-06 14:13 UTC, laurentmahieu submitted a review, later dismissed

2019-12-06 14:23 UTC, LoicBrassart requested changes
Almost perfect ;-)

2019-12-06 14:23 UTC, LoicBrassart commented on frontend/src/components/ListCar.jsx
> +  const [notif, setNotif] = useState(<NotifCard />);
... I never thought of doing that O.o
It works ? That's great! :+1:

2019-12-06 14:23 UTC, LoicBrassart commented on frontend/src/components/style/ListCar.scss
> +  --gradientColor3: #00dc9f;
You shouldn't add new colors in other files than `index.scss`, as they'll overwrite the main ones and it will prove quite difficult to debug

2019-12-09 09:20 UTC, laurentmahieu submitted a review, later dismissed

2019-12-09 09:24 UTC, laurentmahieu submitted a review, later dismissed

2019-12-11 10:59 UTC, LoicBrassart submitted a review, later dismissed
SnE

2019-12-11 11:53 UTC, laurentmahieu approved these changes

2019-12-12 15:56 UTC, LoicBrassart approved these changes
SnE

2019-12-12 16:00 UTC, merged