adding fonts files for general style
WildCodeSchool/lille-0919-js-projet3-shinyHedgehog pull request #2
Opened 2019-12-04 15:51 UTC by Oluane

2019-12-04 15:54 UTC, laurentmahieu submitted a review, later dismissed

2019-12-05 08:14 UTC, LoicBrassart requested changes
- `Visuels` is a very bad directory name (French + capital letter). Please use `pictures` or `pics` instead
- Fonts are not pictures, add them to a `fonts` directory ;-)

2019-12-05 08:22 UTC, laurentmahieu approved these changes

2019-12-05 08:26 UTC, LoicBrassart approved these changes
👌

2019-12-05 08:29 UTC, merged