Us5 km update
WildCodeSchool/lille-0919-js-projet3-shinyHedgehog pull request #20
Opened 2019-12-17 16:11 UTC by Oluane

2019-12-17 17:17 UTC, BlandineM commented on frontend/src/components/style/NavBar.scss
> +      // justify-content: center;
comment

2019-12-17 17:50 UTC, Oluane commented on frontend/src/components/style/NavBar.scss
> +      // justify-content: center;
done ;)

2019-12-17 17:51 UTC, LoicBrassart requested changes
Minor fixes to do, it won't take too long

2019-12-17 17:51 UTC, LoicBrassart commented on frontend/src/reducer/reducer.js
> +        case "erase":
I think this is bugged: You could enter the case (`action.value==='erase'`) and *not* enter the if (`numOfKmUpdates<6`). In this specific case: you wouldn't do anything but would not leave the switch, leading to the execution of all other cases ! :scream: 
More seriously, just get the `break` out of the `if`, just as you did in the lower case ;-)

2019-12-17 17:51 UTC, LoicBrassart commented on frontend/src/components/style/NavBar.scss
> +      // justify-content: center;
I'd say even more: dead code ! é_è

2019-12-17 17:51 UTC, LoicBrassart commented on frontend/src/components/KmUpdate.jsx
> +  console.log(typeof keyboard[11]);
No `console.log` on my `dev` branch !

2019-12-17 20:47 UTC, BlandineM submitted a review, later dismissed

2019-12-17 21:00 UTC, Oluane commented on frontend/src/components/KmUpdate.jsx
> +  console.log(typeof keyboard[11]);
Shame on me !

2019-12-18 07:57 UTC, BlandineM submitted a review, later dismissed

2019-12-19 09:38 UTC, laurentmahieu approved these changes

2020-01-02 16:26 UTC, LoicBrassart approved these changes
Seems good to me !

2020-01-02 16:43 UTC, merged