Securised router
WildCodeSchool/lille-0919-js-projet3-shinyHedgehog pull request #46
Opened 2020-01-17 13:45 UTC by dderancourt

you can now naviguate only if you are log

2020-01-17 14:25 UTC, laurentmahieu requested changes

2020-01-17 14:25 UTC, laurentmahieu commented on frontend/src/App.js
> +import React, { Component, useReducer } from "react";
useReducer isn't called, normal?

2020-01-17 14:25 UTC, laurentmahieu commented on backend/package.json
> +    "cookies": "^0.8.0",
are we using this ?

2020-01-17 16:01 UTC, laurentmahieu submitted a review, later dismissed

2020-01-17 16:04 UTC, laurentmahieu submitted a review, later dismissed

2020-01-17 16:56 UTC, laurentmahieu approved these changes

2020-01-20 11:24 UTC, LoicBrassart approved these changes
SnE

2020-01-20 11:26 UTC, merged